---
abstract: 'Perl statement finder'
author:
  - 'This library is free software; you can redistribute it and/or modify'
build_requires:
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.12.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-GitGrepPerlStatement
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::GitGrepPerlStatement:
    file: lib/App/GitGrepPerlStatement.pm
    version: '0.03'
  App::GitGrepPerlStatement::StatementFinder:
    file: lib/App/GitGrepPerlStatement/StatementFinder.pm
requires:
  List::MoreUtils: '0'
  PPI: '0'
  Term::ANSIColor: '0'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/hitode909/git-grep-perl-statement/issues
  homepage: https://github.com/hitode909/git-grep-perl-statement
  repository: git://github.com/hitode909/git-grep-perl-statement.git
version: '0.03'
x_contributors:
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'hitode909 <hitode909@gmail.com>'
